name: demo

#extensions:
#  - name: zipkin
    
services:

  - name: Frontend
    project: Frontend/Frontend.csproj
    env:
      - name: ASPNETCORE_ENVIRONMENT
        value: Development
    bindings:
      - name: http
        port: 8010
        
  - name: Admin
    project: Admin/Admin.csproj
    env:
      - name: ASPNETCORE_ENVIRONMENT
        value: Development
    bindings:
      - name: http
        port: 8020
    
  - name: Registration
    project: Registration/Registration.csproj
    env:
      - name: ASPNETCORE_ENVIRONMENT
        value: Development
    bindings:
      - name: http
        port: 8030

  - name: Backend
    project: Backend/Backend.csproj
    env:
      - name: ASPNETCORE_ENVIRONMENT
        value: Development
    bindings:
      - name: http
        port: 5000
      - name: grpc
        port: 5001

  - name: db
    image: postgres:latest
    env:
      - name: POSTGRES_USER
        value: postgres
      - name: POSTGRES_PASSWORD
        value: password
      - name: POSTGRES_DB
        value: saas
    bindings:
      - port: 5432
    
